### PR TITLE
Update dependencies to latest versions

### PR DESCRIPTION
**Pull request by lextiz**
Hi @bethesque, could you please review this PR? Thanks!

### CODE REVIEW

**Comment by SchulteDev** [comment]
@bethesque ?

**Comment by SchulteDev** [comment]
@lextiz I cannot build your image

    $ docker build -t dius/pact-provider-verifier-docker .
    ...
    ERROR:  While executing gem ... (OptionParser::InvalidOption)
         invalid option: --no-ri

Fix is to edit the Dockerfile-line _gem install bundler --no-ri --no-rdoc_ to

        gem install bundler

**Comment by k-ong** [comment]
Looks good to me too!

**Comment by bethesque** [comment]
This docker image has been made redundant by https://cloud.docker.com/u/pactfoundation/repository/docker/pactfoundation/pact-cli which exposes ALL the options for the `pact verify` command.

**Comment by SchulteDev** [comment]
I think @bethesque wants to point to https://hub.docker.com/r/pactfoundation/pact-cli

**Pull request merged**
