### PR TITLE
Going to latest ruby2-alpine image as base docker image

### PR DESCRIPTION
**Pull request by SchulteDev**
Minimizing image size for image pact-provider-verifier-docker

    > patched:  dius/pact-provider-verifier-docker  my-ms  ...   84.6MB
    > original: dius/pact-provider-verifier-docker  latest ...   747MB

### CODE REVIEW

**Comment by mefellows** [comment]
@bethesque I think we should use this great work and create an official 'mock service'. Thoughts?

**Comment by bethesque** [comment]
I ❤️ it.

**Comment by bethesque** [comment]
Plus, we need some more repos.

**Comment by mefellows** [comment]
🤕

**Comment by bethesque** [comment]
Question - if [ruby alpine](https://hub.docker.com/r/library/ruby/tags/) is only 28MB, where does the other 56mb come from? Is that just because it's uncompressed?

**Comment by SchulteDev** [comment]
There was indeed some space left for reducing the docker-image size even more. For the most recent version (3a4a9f63435c31e30d25c441900503fa62a4046c), image size is now 68.1MB (local).
I don't know, where exactly 28MB for compressed ruby:alpine come from; for investigation, I have used local images

```
dius/pact-provider-verifier-docker  my-ms    ...        29 minutes ago      68.1MB
ruby                                2-alpine ...        11 days ago         61.2MB
```

Inside the images, we got now a diff of **11.7M**

    # patched
    / # du -sh .
    83.7M	.

    # ruby:2-alpine
    / # du -sh .
    72.0M	.

This size-difference comes from `/usr/local/bundle/`, which is (almost) empty in _ruby:2-alpine_, but contains some stuff in (this) pact-provider-verifier-docker

```
/ # du -h /usr/local/bundle/ -d 1 | sort -k 2
11.7M	/usr/local/bundle/
56.0K	/usr/local/bundle/bin
4.0K	/usr/local/bundle/build_info
4.0K	/usr/local/bundle/doc
264.0K	/usr/local/bundle/extensions
11.2M	/usr/local/bundle/gems
128.0K	/usr/local/bundle/specifications
```

I am not experienced in developing Ruby :-D _/usr/local/bundle/gems_ is required. But maybe there is a way of building this image in a different way, so that it can be deleted.

**Comment by mefellows** [comment]
That makes sense to me, at least at a macro level. A number of the gems need to compile and link to libraries (hence requirement for glibc), and when you add up all of the transitive dependencies that probably is reasonable.

Worth looking into for someone who has the time and understanding, but zipped up and cached that's not very big IMO.

**Comment by bethesque** [comment]
I think it's ok too, but was curious. The 28mb came from the tags page on docker hub.

**Comment by bethesque** [comment]
So, are we merging?

**Comment by bethesque** [comment]
👍

**Comment by SchulteDev** [comment]
https://hub.docker.com/r/dius/pact-provider-verifier-docker/tags/
30MB :-) (vs 28MB for ruby:2-alpine)

Local, uncompressed 68.1MB vs 61.2MB

**Comment by mefellows** [comment]
This is awesome, thanks @SchulteMarkus!

**Comment by bethesque** [comment]
#winning

**Pull request merged**
